name: post_tweet

on:
  schedule:
    - cron: '10 * * * *'  # dijalankan setiap  10 menit

jobs:
  post-tweet:
    runs-on: macos-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Instal paket rtweet
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Instal paket ggplot2
        run: Rscript -e 'install.packages("ggplot2", dependencies = TRUE)'
      - name: Eksekusi Script R
        run: Rscript tweet-bot.R